class ports():
    portsUsed = {
        'nightly' : {
                    'FACEBOOK_LISTENER_THRIFT_SERVICE' : 9231,
                    'FACEBOOK_GATEWAY_THRIFT_SERVICE' : 9241,
                    'TEMPORAL_ENGINE_THRIFT_SERVICE' : 8091,
                    'VENENO_LISTENER_THRIFT_SERVICE' : [8191],
                    'CAMPAIGN_SHARD_THRIFT_SERVICE' : [9991],
                    'NSADMIN_THRIFT_SERVICE' : [9881],
                    'COMMENGINE_THRIFT_SERVICE': [9891],
                    'CommDeliveryServer' : 9681,
                    'EMF_THRIFT_SERVICE' : [9191],
                    'LUCI_THRIFT_SERVICE' : [9331],
                    'DRACARYS_THRIFT_SERVICE' : [9601],
                    'DARK_KNIGHT_THRIFT_SERVICE' : 8101,
                    'PEB_THRIFT_SERVICE' : 9801,
                    'INTOUCH_DB_MYSQL_MASTER' : [8911, 8921],
                    'INTOUCH_DB_MYSQL_BILLDUMP' : [8711],
                    'INTOUCH_META_DB_MYSQL' : [8411],
                    'CAMPAIGN_SHARD_DB_MYSQL' : [8911],
                    'NSADMIN_DB_MYSQL' : [8911],
                    'CONQUEST_DB_MYSQL_SHARD' : [6611],
                    'TIMELINE_DB_MYSQL' : [8911],
                    'DARK_KNIGHT_DB_MYSQL' : [8911],
                    'INTOUCH_DB_MONGO_MASTER' : 27011,
                    'CAMPAIGNS_DB_MONGO_MASTER': 27051,
                    'SHARINGAN_DB_MONGO' : 27021,
                    'REON_METADATA_API_THRIFT_SERVICE':[8891]
        },
        'staging' : {
                    'FACEBOOK_LISTENER_THRIFT_SERVICE' : 9232,
                    'FACEBOOK_GATEWAY_THRIFT_SERVICE' : 9242,
                    'VENENO_LISTENER_THRIFT_SERVICE' : [8192],
                    'CAMPAIGN_SHARD_THRIFT_SERVICE' : [9992],
                    'NSADMIN_THRIFT_SERVICE' : [9882],
                    'COMMENGINE_THRIFT_SERVICE': [9892],
                    'TEMPORAL_ENGINE_THRIFT_SERVICE' : 8092,
                    'CommDeliveryServer' : 9682,
                    'EMF_THRIFT_SERVICE' : [9192],
                    'LUCI_THRIFT_SERVICE' : [9332],
                    'DRACARYS_THRIFT_SERVICE': [9602],
                    'DARK_KNIGHT_THRIFT_SERVICE' : 8102,
                    'PEB_THRIFT_SERVICE' : 9802,
                    'INTOUCH_DB_MYSQL_MASTER' : [8912, 8922],
                    'INTOUCH_DB_MYSQL_BILLDUMP' : [8712],
                    'INTOUCH_META_DB_MYSQL' : [8412],
                    'CAMPAIGN_SHARD_DB_MYSQL' : [8912],
                    'NSADMIN_DB_MYSQL' : [8912],
                    'CONQUEST_DB_MYSQL_SHARD' : [6612],
                    'TIMELINE_DB_MYSQL' : [8912],
                    'DARK_KNIGHT_DB_MYSQL' : [8712],
                    'INTOUCH_DB_MONGO_MASTER' : 27012,
                    'CAMPAIGNS_DB_MONGO_MASTER': 27052,
                    'SHARINGAN_DB_MONGO' : 27022,
                    'REON_METADATA_API_THRIFT_SERVICE':[8892]
        },
        'more' : {
                    'FACEBOOK_LISTENER_THRIFT_SERVICE' : 9233,
                    'FACEBOOK_GATEWAY_THRIFT_SERVICE' : 9243,
                    'VENENO_LISTENER_THRIFT_SERVICE' : [8193],
                    'CAMPAIGN_SHARD_THRIFT_SERVICE' : [9993],
                    'NSADMIN_THRIFT_SERVICE' : [9883],
                    'COMMENGINE_THRIFT_SERVICE': [9893],
                    'TEMPORAL_ENGINE_THRIFT_SERVICE' : 8093,
                    'CommDeliveryServer' : 9683,
                    'EMF_THRIFT_SERVICE' : [9193, 9183, 9173],
                    'LUCI_THRIFT_SERVICE' : [9333],
                    'DRACARYS_THRIFT_SERVICE': [9603],
                    'DARK_KNIGHT_THRIFT_SERVICE' : 8103,
                    'PEB_THRIFT_SERVICE' : 9803,
                    'INTOUCH_DB_MYSQL_MASTER' : [8913, 8923, 8933, 8943,8953,8963,8973],
                    'INTOUCH_DB_MYSQL_BILLDUMP' : [8713],
                    'INTOUCH_META_DB_MYSQL' : [8413],
                    'CAMPAIGN_SHARD_DB_MYSQL' : [8513],
                    'NSADMIN_DB_MYSQL' : [8313],
                    'CONQUEST_DB_MYSQL_SHARD' : [6613, 6623, 6633],
                    'TIMELINE_DB_MYSQL' : [8713],
                    'DARK_KNIGHT_DB_MYSQL' : [8313],
                    'INTOUCH_DB_MONGO_MASTER' : 27013,
                    'CAMPAIGNS_DB_MONGO_MASTER': 27053,
                    'SHARINGAN_DB_MONGO' : 27023,
                    'REON_METADATA_API_THRIFT_SERVICE':[8893]
        },
        'india' : {
                    'FACEBOOK_LISTENER_THRIFT_SERVICE' : 9234,
                    'FACEBOOK_GATEWAY_THRIFT_SERVICE' : 9244,
                    'VENENO_LISTENER_THRIFT_SERVICE' : [8194],
                    'CAMPAIGN_SHARD_THRIFT_SERVICE' : [9994],
                    'NSADMIN_THRIFT_SERVICE' : [9884],
                    'COMMENGINE_THRIFT_SERVICE': [9894],
                    'COMMENGINE_THRIFT_SERVICE': [9894],
                    'TEMPORAL_ENGINE_THRIFT_SERVICE' : 8094,
                    'CommDeliveryServer' : 9684,
                    'EMF_THRIFT_SERVICE' : [9194, 9184],
                    'LUCI_THRIFT_SERVICE' : [9334, 9344],
                    'DRACARYS_THRIFT_SERVICE': [9604],
                    'DARK_KNIGHT_THRIFT_SERVICE' : 8104,
                    'PEB_THRIFT_SERVICE' : 9804,
                    'INTOUCH_DB_MYSQL_MASTER' : [8914, 8924],
                    'INTOUCH_DB_MYSQL_BILLDUMP' : [8714],
                    'INTOUCH_META_DB_MYSQL' : [8414],
                    'CAMPAIGN_SHARD_DB_MYSQL' : [8514],
                    'NSADMIN_DB_MYSQL' : [8314],
                    'CONQUEST_DB_MYSQL_SHARD' : [6614, 6624, 6634, 6644],
                    'TIMELINE_DB_MYSQL' : [8214],
                    'DARK_KNIGHT_DB_MYSQL' : [8314],
                    'INTOUCH_DB_MONGO_MASTER' : 27014,
                    'CAMPAIGNS_DB_MONGO_MASTER': 27054,
                    'SHARINGAN_DB_MONGO' : 27024,
                    'REON_METADATA_API_THRIFT_SERVICE':[8894]
        },
        'eu' : {
                    'FACEBOOK_LISTENER_THRIFT_SERVICE' : 9235,
                    'FACEBOOK_GATEWAY_THRIFT_SERVICE' : 9245,
                    'VENENO_LISTENER_THRIFT_SERVICE' : [8195],
                    'CAMPAIGN_SHARD_THRIFT_SERVICE' : [9995],
                    'NSADMIN_THRIFT_SERVICE' : [9885],
                    'COMMENGINE_THRIFT_SERVICE': [9895],
                    'TEMPORAL_ENGINE_THRIFT_SERVICE' : 8095,
                    'CommDeliveryServer' : 9685,
                    'EMF_THRIFT_SERVICE' : [9195],
                    'LUCI_THRIFT_SERVICE' : [9335],
                    'DRACARYS_THRIFT_SERVICE': [9605],
                    'DARK_KNIGHT_THRIFT_SERVICE' : 8105,
                    'PEB_THRIFT_SERVICE' : 9805,
                    'INTOUCH_DB_MYSQL_MASTER' : [8915,8925],
                    'INTOUCH_DB_MYSQL_BILLDUMP' : [8715],
                    'INTOUCH_META_DB_MYSQL' : [8415],
                    'CAMPAIGN_SHARD_DB_MYSQL' : [8515],
                    'NSADMIN_DB_MYSQL' : [8315],
                    'CONQUEST_DB_MYSQL_SHARD' : [6615],
                    'TIMELINE_DB_MYSQL' : [8315],
                    'DARK_KNIGHT_DB_MYSQL' : [8315],
                    'INTOUCH_DB_MONGO_MASTER' : 27015,
                    'CAMPAIGNS_DB_MONGO_MASTER': 27055,
                    'SHARINGAN_DB_MONGO' : 27025,
                    'REON_METADATA_API_THRIFT_SERVICE':[8895]
        },
        'china' : {
                    'FACEBOOK_LISTENER_THRIFT_SERVICE' : 9237,
                    'FACEBOOK_GATEWAY_THRIFT_SERVICE' : 9247,
                    'VENENO_LISTENER_THRIFT_SERVICE' : [8197],
                    'CAMPAIGN_SHARD_THRIFT_SERVICE' : [9997],
                    'NSADMIN_THRIFT_SERVICE' : [9887],
                    'COMMENGINE_THRIFT_SERVICE': [9897],
                    'TEMPORAL_ENGINE_THRIFT_SERVICE' : 8097,
                    'CommDeliveryServer' : 9687,
                    'EMF_THRIFT_SERVICE' : [9197],
                    'LUCI_THRIFT_SERVICE' : [9337],
                    'DRACARYS_THRIFT_SERVICE': [9607],
                    'DARK_KNIGHT_THRIFT_SERVICE' : 8107,
                    'PEB_THRIFT_SERVICE' : 9807,
                    'INTOUCH_DB_MYSQL_MASTER' : [8917],
                    'INTOUCH_DB_MYSQL_BILLDUMP' : [8717],
                    'INTOUCH_META_DB_MYSQL' : [8417],
                    'CAMPAIGN_SHARD_DB_MYSQL' : [8717],
                    'NSADMIN_DB_MYSQL' : [8317],
                    'CONQUEST_DB_MYSQL_SHARD' : [6617],
                    'TIMELINE_DB_MYSQL' : [8717],
                    'DARK_KNIGHT_DB_MYSQL' : [8315],
                    'INTOUCH_DB_MONGO_MASTER' : 27017,
                    'CAMPAIGNS_DB_MONGO_MASTER': 27057,
                    'SHARINGAN_DB_MONGO' : 27027,
                    'REON_METADATA_API_THRIFT_SERVICE':[8891]
        },
        'local' : {
                    'FACEBOOK_LISTENER_THRIFT_SERVICE' : 9234,
                    'FACEBOOK_GATEWAY_THRIFT_SERVICE' : 9232,
                    'VENENO_LISTENER_THRIFT_SERVICE' : [8092],
                    'CAMPAIGN_SHARD_THRIFT_SERVICE' : [9998],
                    'NSADMIN_THRIFT_SERVICE' : [9881, 9871],
                    'CommDeliveryServer' : 80,
                    'EMF_THRIFT_SERVICE' : [9199],
                    'LUCI_THRIFT_SERVICE' : [9333],
                    'DRACARYS_THRIFT_SERVICE': [3000],
                    'DARK_KNIGHT_THRIFT_SERVICE' : 8100,
                    'PEB_THRIFT_SERVICE' : 9800,
                    'INTOUCH_DB_MYSQL_MASTER' : [3306],
                    'INTOUCH_DB_MYSQL_BILLDUMP' : [3306],
                    'INTOUCH_META_DB_MYSQL' : [3306],
                    'CAMPAIGN_SHARD_DB_MYSQL' : [3306],
                    'NSADMIN_DB_MYSQL' : [3306],
                    'CONQUEST_DB_MYSQL_SHARD' : [3306],
                    'TIMELINE_DB_MYSQL' : [3306],
                    'DARK_KNIGHT_DB_MYSQL' : [3306],
                    'INTOUCH_DB_MONGO_MASTER' : 27017,
                    'CAMPAIGNS_DB_MONGO_MASTER': 27051,
                    'SHARINGAN_DB_MONGO' : [27010],
                    'REON_METADATA_API_THRIFT_SERVICE':[8891]

        }        
    }


     
